# Generated by Django 5.0.6 on 2026-03-19 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('age', models.IntegerField()),
                ('sexe', models.CharField(choices=[('M', 'Homme'), ('F', 'Femme')], max_length=1)),
                ('profession', models.CharField(blank=True, max_length=150)),
                ('motif', models.TextField(blank=True)),
                ('diagnoses', models.JSONField(blank=True, default=list)),
                ('antecedents', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_number', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('clinical_notes', models.TextField(blank=True)),
                ('completed', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='clinical.patient')),
            ],
            options={
                'unique_together': {('patient', 'session_number')},
            },
        ),
        migrations.CreateModel(
            name='PsychometricScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(choices=[('EII', "Échelle d'intolérance à l'incertitude"), ('PSI_II', "Pourquoi s'inquiéter - Version II"), ('QEC', "Questionnaire d'évitement cognitif"), ('QIA', "Questionnaire sur l'inquiétude et l'anxiété (Diagnostic TAG)")], max_length=10)),
                ('raw_answers', models.JSONField()),
                ('total_score', models.FloatField(blank=True, null=True)),
                ('sub_scores', models.JSONField(blank=True, default=dict)),
                ('meets_gad_criteria', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='clinical.patient')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='clinical.treatmentsession')),
            ],
        ),
        migrations.CreateModel(
            name='ImaginalExposureWorksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_theme', models.CharField(max_length=255)),
                ('time_before', models.TimeField(blank=True, null=True)),
                ('distress_before', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)])),
                ('time_after', models.TimeField(blank=True, null=True)),
                ('distress_after', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)])),
                ('max_distress', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)])),
                ('did_neutralize', models.BooleanField(default=False)),
                ('neutralization_comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exposure_sheets', to='clinical.treatmentsession')),
            ],
        ),
        migrations.CreateModel(
            name='AdvantageDisadvantageWorksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adv_disadv_sheets', to='clinical.treatmentsession')),
            ],
        ),
        migrations.CreateModel(
            name='UncertaintyBehaviorWorksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_description', models.TextField()),
                ('discomfort_felt', models.TextField()),
                ('thoughts_during_action', models.TextField()),
                ('observations_after', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uncertainty_sheets', to='clinical.treatmentsession')),
            ],
        ),
    ]
