# Generated by Django 5.0.6 on 2026-03-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychometricscore',
            name='test_name',
            field=models.CharField(choices=[('EII', "Échelle d'intolérance à l'incertitude"), ('PSI_II', "Pourquoi s'inquiéter - Version II"), ('QEC', "Questionnaire d'évitement cognitif"), ('QIA', "Questionnaire sur l'inquiétude et l'anxiété (Diagnostic TAG)"), ('QAP', "Questionnaire d'attitude face aux problèmes"), ('QCS_TAG', 'Questionnaire sur les comportements sécurisants du TAG')], max_length=10),
        ),
    ]
