# Generated by Django 5.2.12 on 2026-03-22 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0002_alter_psychometricscore_test_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevilsAdvocateWorksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belief', models.TextField(verbose_name='Croyance ciblée')),
                ('evidence_for', models.TextField(verbose_name='Preuves pour cette croyance')),
                ('evidence_against', models.TextField(verbose_name='Arguments contre cette croyance')),
                ('advantages_of_belief', models.TextField(verbose_name='Avantages de cette croyance')),
                ('disadvantages_of_belief', models.TextField(verbose_name='Désavantages de cette croyance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devils_advocate_sheets', to='clinical.patient')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devils_advocate_sheets', to='clinical.treatmentsession')),
            ],
            options={
                'verbose_name': 'Fiche Avocat du Diable',
                'verbose_name_plural': 'Fiches Avocat du Diable',
            },
        ),
        migrations.CreateModel(
            name='RelapsePreventionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warning_signs', models.TextField(verbose_name="Signes précurseurs d'une rechute")),
                ('effective_strategies', models.TextField(verbose_name='Stratégies efficaces apprises')),
                ('future_goals', models.TextField(verbose_name='Objectifs futurs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relapse_plans', to='clinical.patient')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relapse_plans', to='clinical.treatmentsession')),
            ],
            options={
                'verbose_name': 'Plan de prévention de la rechute',
                'verbose_name_plural': 'Plans de prévention de la rechute',
            },
        ),
        migrations.CreateModel(
            name='WorryLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_slot', models.CharField(choices=[('morning', 'Matin'), ('afternoon', 'Après-midi'), ('evening', 'Soir')], max_length=10)),
                ('worry_description', models.TextField(verbose_name="Description de l'inquiétude")),
                ('anxiety_level', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8')], verbose_name="Niveau d'anxiété (0-8)")),
                ('worry_type', models.CharField(choices=[('actual', 'Problème réel'), ('hypothetical', 'Problème éventuel')], max_length=15, verbose_name="Type d'inquiétude")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worry_logs', to='clinical.patient')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worry_logs', to='clinical.treatmentsession')),
            ],
            options={
                'verbose_name': "Entrée du carnet d'inquiétudes",
                'verbose_name_plural': "Entrées du carnet d'inquiétudes",
                'ordering': ['-date', 'time_slot'],
            },
        ),
    ]
