# Generated by Django 5.0.6 on 2026-03-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0003_devilsadvocateworksheet_relapsepreventionplan_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treatmentsession',
            options={'ordering': ['session_number']},
        ),
        migrations.AlterUniqueTogether(
            name='treatmentsession',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='treatmentsession',
            name='is_intermediate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='treatmentsession',
            name='parent_session_number',
            field=models.IntegerField(blank=True, help_text='For intermediate sessions: the protocol session whose exercises are inherited.', null=True),
        ),
        migrations.AlterField(
            model_name='treatmentsession',
            name='session_number',
            field=models.FloatField(),
        ),
    ]
